import * as functions from "firebase-functions";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({apiKey: process.env.API_KEY});

export const generateWelcomeMessage = functions.region("europe-west1").https.onCall(async (data, context) => {
  const { firstName } = data;
  if (!firstName || typeof firstName !== 'string') {
    throw new functions.https.HttpsError("invalid-argument", "The function must be called with a 'firstName' argument.");
  }

  try {
    const prompt = `Génère un message de bienvenue très court, chaleureux et légèrement futuriste pour un nouvel utilisateur nommé "${firstName}" qui s'inscrit à "Helper", une application premium de services à domicile en Côte d'Ivoire. Le ton doit être rassurant et professionnel. Le message doit être en français. Ne mets pas de guillemets autour du message.`;

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
    });
    
    const text = response.text;

    if (!text) {
        throw new Error("No text generated by Gemini.");
    }
    
    return { text: text.trim() };

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    return { text: `Bienvenue à bord, ${firstName} ! Helper est ravi de vous compter parmi nous.` };
  }
});